- hosts: web
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - nginx

    - name: create dir
      command: mkdir -p /usr/www/html

    - name: sync html
      synchronize:
        src: html/index.html
        dest: /usr/www/html/index.html

    - name: sync nginx sites setting
      synchronize:
        src: nginx/mynet
        dest: /etc/nginx/sites-available

    - name: set link
      shell: |
        ln -fsv /etc/nginx/sites-available/mynet /etc/nginx/sites-enabled/mynet
        if [ -f /etc/nginx/sites-enabled/default ]; then
          rm -rf /etc/nginx/sites-enabled/default
        fi

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.web
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved

    - name: run nginx
      command: systemctl restart nginx

- hosts: dns
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - unbound

    - name: sync unbound conf
      synchronize:
        src: unbound/mynet.conf
        dest: /etc/unbound/unbound.conf.d/mynet.conf

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.dns
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved

    - name: change permission
      shell: |
        chmod 755 /etc/unbound/unbound.conf.d/mynet.conf

    - name: run unbound
      command: systemctl restart unbound

- hosts: revprx
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - nginx

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.revprx
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved
