- hosts: web
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: set yarn repository
      shell: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - nginx
        # ruby
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm5
        - libgdbm-dev
        # yarn
        - yarn

    - name: create dir
      command: mkdir -p /usr/www/html

    - name: sync html
      synchronize:
        src: html/index.html
        dest: /usr/www/html/index.html

    - name: sync nginx sites setting
      synchronize:
        src: nginx/mynet.web
        dest: /etc/nginx/sites-available/mynet

    - name: set link
      shell: |
        ln -fsv /etc/nginx/sites-available/mynet /etc/nginx/sites-enabled/mynet
        if [ -f /etc/nginx/sites-enabled/default ]; then
          rm -rf /etc/nginx/sites-enabled/default
        fi

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.web
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved

    - name: run nginx
      command: systemctl restart nginx

    - name: install ruby-build
      shell: |
        cd /home/vagrant
        git clone --depth=1 https://github.com/rbenv/ruby-build.git
        PREFIX=/usr/local ./ruby-build/install.sh

    - name: install ruby 2.5.5
      shell: |
        if [ ! -d /usr/local/bin/ruby ]; then
          ruby-build 2.5.5 /usr/local/bin/ruby
        fi

    - name: install n (node version manager)
      shell: |
        if [ ! -d /home/vagrant/n ]; then
          curl -L https://git.io/n-install | bash
        fi

    - name: install node 13.11.0
      shell: |
        if [ ! -f /usr/local/bin/node ]; then
          n 13.11.0
        fi

- hosts: dns
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - unbound

    - name: sync unbound conf
      synchronize:
        src: unbound/mynet.conf
        dest: /etc/unbound/unbound.conf.d/mynet.conf

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.dns
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved

    - name: change permission
      shell: |
        chmod 755 /etc/unbound/unbound.conf.d/mynet.conf

    - name: run unbound
      command: systemctl restart unbound

- hosts: revprx
  remote_user: root
  become: true
  gather_facts: no
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        pkg:
        - nginx

    - name: sync nginx sites setting
      synchronize:
        src: nginx/mynet.revprx
        dest: /etc/nginx/sites-available/mynet

    - name: set link
      shell: |
        ln -fsv /etc/nginx/sites-available/mynet /etc/nginx/sites-enabled/mynet
        if [ -f /etc/nginx/sites-enabled/default ]; then
          rm -rf /etc/nginx/sites-enabled/default
        fi

    - name: sync resolved.conf
      synchronize:
        src: systemd/resolved.conf.revprx
        dest: /etc/systemd/resolved.conf

    - name: restart systemd-resolved
      command: systemctl restart systemd-resolved

    - name: run nginx
      command: systemctl restart nginx
